---
version: 2
jobs:
  test:
    working_directory: /app
    docker:
      - image: thechangelog/runtime:2018-11-23.103218
      - image: circleci/postgres:9.5.17
        environment:
          POSTGRES_USER: "postgres"
          POSTGRES_DB: changelog_test
          POSTGRES_PASSWORD: "postgres"
    steps:
      - checkout
      - restore_cache:
          name: Restore cached deps
          key: deps-{{ checksum "mix.lock" }}
      - restore_cache:
          name: Restore cached build
          key: build-{{ checksum "mix.lock" }}
      - run:
          name: Wait for PostgreSQL
          command: timeout 60 bash -c "while sleep 1; do nc -zv 127.0.0.1 5432 && break; done"
      - run:
          name: Run tests
          command: |
            export MIX_ENV=test
            echo "Drop $MIX_ENV db..."
            mix ecto.drop --force
            echo "Run tests..."
            if [ "$CIRCLE_BRANCH" = "master" ]
            then
              mix coveralls.circle
            else
              mix test
            fi
workflows:
  version: 2
  build:
    jobs:
      - test
